import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Home } from './Home'
import { Header } from '../components/Header'
import { WineInfo } from './WineInfo'

const App: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      
      <Home />
    </div>
  )
}

export default App
